_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  META_ARCHITECTURE: "SparseRCNNWSDDN"
  WEIGHTS: "models/VGG_ILSVRC_16_layers_v1_d2.pkl"
  PIXEL_MEAN: [103.939, 116.779, 123.68]
  PIXEL_STD: [1.0, 1.0, 1.0]
  BACKBONE:
    NAME: "build_vgg_backbone"
    FREEZE_AT: 5
  VGG:
    DEPTH: 16
    CONV5_DILATION: 1
  SparseRCNN:
    NUM_HEADS: 1
    HIDDEN_DIM: 512
    # NUM_PROPOSALS: 8100
    NUM_PROPOSALS: 3600
    NUM_CLASSES: 20
    USE_FOCAL: False
  ROI_HEADS:
    IN_FEATURES: ["plain5"]
    PROPOSAL_APPEND_GT: False
    SCORE_THRESH_TEST: 0.000000001
    # IOU_THRESHOLDS: [0.5]
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIPool"
    NUM_FC: 2
    # FC_DIM: [4096, 4096]
    FC_DIM: 4096
DATASETS:
  TRAIN: ('voc_2007_train', 'voc_2007_val')
  TEST: ('voc_2007_test',)
# TEST:
#   EVAL_PERIOD: 4
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  BASE_LR: 0.001
  OPTIMIZER: "SGD" 
  BASE_LR: 0.001
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0005
  BIAS_LR_FACTOR: 2.0
  WEIGHT_DECAY_BIAS: 0.0

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216)
  # MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 688
  MAX_SIZE_TEST: 2000
  CROP:
    ENABLED: False
  FORMAT: "BGR"
