_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  META_ARCHITECTURE: "SparseRCNNOICR"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 800
    NUM_CLASSES: 20
    DEEP_SUPERVISION: False
  ROI_BOX_HEAD:
    NUM_FC: 2
    # FC_DIM: [4096, 4096]
    FC_DIM: 4096
DATASETS:
  TRAIN: ('voc_2007_train', 'voc_2007_val')
  TEST: ('voc_2007_test',)
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
